[project]
name = "pr"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "chainlit>=2.5.5",
    "openai-agents>=0.0.14",
    "pdfplumber>=0.11.6",
    "pinecone>=6.0.2",
    "sentence-transformers>=4.1.0",
]
